### ISSUE TITLE
curl: (7) Failed to connect to localhost port 3000: Connection refused

### ISSUE THREAD

**Issue by flik** [HugoDF/express-redis-docker#1]
here is output:

$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
153d47840c64        express-redis-docker_app   "sh -c 'npm i && nod…"   13 minutes ago      Up 4 seconds        0.0.0.0:3000->3000/tcp   express-redis-docker_app_1
1d0b3e56d40b        redis                      "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes       6379/tcp                 cache

$ curl http://localhost:3000/store/my-key\?some\=value\&some-other\=other-value
curl: (7) Failed to connect to localhost port 3000: Connection refused

**Comment by stelcodes** [comment]
i'm having the same problem!!

**Comment by gabriel-soga-movile** [comment]
same here
